services:
  rstudio:
    build: .
    image: rstudio-rstudio-1
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=""
      - DISABLE_AUTH=true
      - USERID=1000
      - GROUPID=1000
    command: >
      bash -lc "mkdir -p /home/rstudio/project/data /home/rstudio/project/plots_rstudio /home/rstudio/project/docs &&
      chown rstudio:rstudio /home/rstudio/project &&
      chown -R rstudio:rstudio /home/rstudio/project/data /home/rstudio/project/plots_rstudio /home/rstudio/project/docs &&
      chmod a+rwX /home/rstudio/project &&
      chmod -R a+rwX /home/rstudio/project/data /home/rstudio/project/plots_rstudio /home/rstudio/project/docs &&
      umask 000 &&
      /init"
    volumes:
      - .:/home/rstudio/project
    restart: unless-stopped
